/**
 * falcon_verify — Initiative 06 integration tests
 *
 * Run with: anchor test --skip-deploy
 *
 * Test suite:
 *   1. initialize_keyring — creates the SigningKeyring PDA, appends audit leaf
 *   2. verify_signature — real ML-DSA-44 test vectors, correct lengths → accepted
 *   3. verify_signature — wrong signature length → BadSignatureLength error
 *   4. verify_signature — wrong public-key length → BadPublicKeyLength error
 *   5. rotate_signing_key — old key authorizes new key; PDA updated; audit leaf appended
 *   6. rotate_signing_key — unauthorized rotation rejected (RotationNotAuthorized)
 *   7. Falcon-512 verify_signature → FalconNotYetSupported (no simd-0416 feature)
 *
 * Real ML-DSA-44 test vectors generated by:
 *   cargo test -p falcon_verify print_test_vectors -- --nocapture
 * Seed 1 → old keypair (keyring initial key / test-message signer)
 * Seed 2 → new keypair (rotation target)
 *
 * BPF note: on-chain verify_dilithium3 is a structural stub (length checks only).
 * ml-dsa's expand_a builds NttMatrix<4,4> (~16 KB) on the stack before boxing it,
 * exceeding the 4 KB BPF per-frame limit. The 7 Rust unit tests (cargo test -p
 * falcon_verify) exercise real ML-DSA-44 verification including tampered-sig
 * rejection. On-chain cryptographic verification is performed off-chain by the
 * RIA's compliance system before any instruction is submitted.
 */

import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import {
  ComputeBudgetProgram,
  Keypair,
  PublicKey,
  SystemProgram,
  Transaction,
} from "@solana/web3.js";
import {
  getConcurrentMerkleTreeAccountSize,
} from "@solana/spl-account-compression";
import { assert } from "chai";

// Program IDs from Anchor.toml [programs.localnet]
const AUDIT_MERKLE_ID  = new PublicKey("86GxUKYc4kxmmi8raLPorRy9kobNgYn4YYwzpjdPk5UM");
const FALCON_VERIFY_ID = new PublicKey("CCFsAnMbTkuoBE2WkQFz5dANybWjCcNmHbPrV4A9T3oR");
const SPL_COMPRESSION  = new PublicKey("cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK");
const SPL_NOOP         = new PublicKey("noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV");

const DILITHIUM3_SIG_LEN  = 2420;
const DILITHIUM3_PK_LEN   = 1312;
const FALCON512_SIG_LEN   = 690;
const FALCON512_PK_LEN    = 897;

const MAX_DEPTH       = 20;
const MAX_BUFFER_SIZE = 64;

const SIG_TYPE_DILITHIUM3 = { dilithium3: {} };
const SIG_TYPE_FALCON512  = { falcon512: {}  };

// PqBuffer write chunk size — must fit inside Solana's 1232-byte tx limit.
const CHUNK = 900;

// ── Real ML-DSA-44 test vectors ──────────────────────────────────────────────
// Generated by: cargo test -p falcon_verify print_test_vectors -- --nocapture
// Seed 1 = old key (initial keyring + signs test message)
// Seed 2 = new key (rotation target)
const MSG_BYTES = Buffer.from("zynt-protocol-test-message");

const PK1_HEX = "5ece0a3d6c14bad171412c9b72087d8dc191258d6c106bba7f2850c720187c7fefa4279ceb692fac178c411c8d00436a27246584cd576ca1a5bcb05b595270f173460ea64724cb5427ac61f9e1205c1dc9c0408567d2416197b7ea7a78e969ec2f99c73a4c6b7228eb49e362e17d5d5d5189802d1e0d4132e07b4ec9bfe6e18556eafbbfbd4d392a5a5bb0e14ddf2f48aed881d748b28179337066a395f9907998764da58d5acb70738b618e4682bbabd78d0102e896f2e35b9fb9c4aa257dcdc47ef7c2d8a906b80c7e71a582813708f6d67bb63ce00ae73753b95eb1a6ebb669b608e65f4f99b03604a676b035ad723e456df5885194e111f8f9a0bc60140577058b91b851c92cf746bb0f4a8fdb132204261f8bef290cf32366b20f8781c0b4609348a4bf3b517526dab38e70346f6129ca6297aa4a4589d05eea7b677fb48aaea7ae1018c5f9636e525ed47849330cd81058a8e255f0a4ad136d254b3b760e95c8bb1b9c1a1c13c37d03f2507f1f49e4f3326e19ba44713e349752aeaa18c01e4ded1e5d87657d495f01ce00523f809f6ab5292b21ca4e4aa5f46c0da134bccea1c82efc41287a2c06ff52ef385113556aaa2d5821f3eaeba3855bea38365e60f10d14d0b641e6a2fe31f9d6d5a5e4b2bc5756668de75ca75204dc67dd100f13b9ef6ad97c207baf5e32b4705484ea149300ae9ae6f371b0a5be8b9008a922d1a263cfd6307e711a308add3df443593ec123d8ed09b66d01df761c0f62a992ac97dd1e08bcff7b935efb5805cc03b12e10fb61c8d445e885ae022bd44c64c2cf10faa7be7830f502e9d60d8774e5e111d1ec2e1c9c30fdb588a86f73e6f3cfa5cebd6cf08651b907b097577c706a7d8c3a340d4be2dff27cf3e24d806b7de3acf6394f1d25d8b19d87334f6c4a3b946f8ad04adf02895b165f6aa2a17617488126713ac4d96d6323e5b3445aa702af57fe7fddcd99e0904cf923660436252cc85473d2b584ba24b9a7978f690dc58550196522672fb7a5180d0f39988355f9aa6a11e246c2c8c9ea4d36265f8fcaa112f4a0a765c88ea03aa55565780f36458054f1a143ce7447da17262864b9c61dc4c78663c74f57e5313144c2f3ad677c14b9ac055002ba3b3507c25a060f5330a52f2a09950b3792fade4aea1597413f7b81a9b8ccc94ed6bc009953894db58743685263d61e4fcfce0b46c0af1ec3d8338d97db297b34a9e745648b9f9def46ca96d17033659494254ea43a42c0e1f882ccda136de05c2fc2d1ba892603a6c430d416420f6c30dcdbd3fb92f204d68b1879de016c861c46f61f0ded2e28361de277ecccc3657a209ddaaaf6c58d7d92ad063c6469e73b30f21596bf70ff09e63928587ca82d261f54aec5569609991c652de276cb4912ee5a54e3c0a5975f93e3b783f69b2ec172e1e9dba9838ac9f0648c6cc7a9a7a963326c15c12b5e0d8216b3b0844c67b3fed2c5f22b4ff882141933de89ddc666dff6aeb0ccf6297b907bd84ed90bb62766f263c1e5ef4e38bc587740e4f447d04f7d9ac374dceff9ddb1f151ccde56afaaa98c9a53c73c34dcaae37a38ac26bffdc4fc1ac1d0041be56dadf7ae799c6b4bf50ff27f5675a3d6cdfd23f859d00f275b483a17b5cc45ac0d827708b1b374acee6bfae7988e82b121e5bd76f78d527420880aabddfa98f4ba18e32244327b3e27b0711ec28f6246e7ea749a5e6beacd56dee8ef7adee20cca3f6f9e9205590ec21e330e81e35786c63500bbaae63e49a2411ba89b85a9dfdb9d379462ddb38b7d5195ffa573b4628fcf5a4e76a056786dac9da8d227566c45179c5bb26ce4fd7a09fc63582a8a";
const SIG1_HEX = "a9173657dceed160b645ffb310611c97be26defa3a12c4a84aa2a59798d7619b5dfc2e69cf27427b3f6292fa558d34161577f167a8f3d4bed7ab7e21abe8d5aaff8bc941ca3da2b2565daf0e59e1b8384a432cf68d78603b6826d94d6f6949e896c482565d27f6ee139c89fe1f71addefdbe40adadc3eaeb6f7803ed441243152ec1e05f32bf0b7b5b4b87b6f94439d42627162f8e5e712d9400817d07b83f40510b80ca04f28f85f75befd7c74c1451c4d6c38256e5d5ca53a79bec8eebd8ca8f73bd3701cff70fb35bf109a0412a7d065568386c1ed25b8ffc4237a77d1210864040f2fe8910051f4a30e96eec23463313fb5894735fad42b5ce3173b6a6c3e28790429ef7642b439151b3fc96adb3681511cd76839b40fec0c226b8d1d45c402980a20201dbd1dd1573be58e9575f4708e4bba4633a296bfa0826774bf30b397c55f3a2bef5ede66d585de14763773bbe1ad3d2e988a9e94e467191888d784a2092cc5aa172d17a07a07076c40896ed947fd9514fafb2f125aecf174e31ede1d77112e978449ef58bb54bb48678eca38323356f40b6c9fdfb1f14faaffc7f3c86f201162c2527cb705f8759d48b3301f8206a1a71a683cbe4d70b8858c7a6466eade39c3fd1c6256d75a1569ca7642f884750e3d080139fd71f4ed5a0ac2b92bb6a68128207bf1cf5eb3297fa0b2c63115c49619aa2355279202d0785485318d6bf239b6968fb289b6ffdc18f035d08a0f49d9d1322b82a7b8f30ad8c391af34c4f0e3eeb5f182f0b91dcc9571f7198f5f31342469158bff3ad1b77ae057a9e570a2f408393d05fd28ce6fb265e439ed2fc35eaecb6351aecdec57b1842d010f64a6bf4cc826609f433a40a02d311fe37572c2ec13f865a1119d607564139c8294fb450dd235df70ca052c09bfea8e600cc4ea07048677a3eb78b2ca9f1c256fbdd73d18718a273fae598314c1ea3ae3933d5ef43efd52e0919497c5a1ef8089f610dedd2d5910c5c1127ea6fbf827fb151ad666006a8161399e78fbccada995823988ff334d92406b9140ca857f64230eb5221243eac31ddce1a6cfc393bcf51e299287610eb303f6833caeedd4c29a7d15e9d434c2a23e31f85c129010df0822ebf6523ae368d8c46894f1a14dedb75ec664733b057c06f0833c11a05d07f54be77f0b9af867435f102e1b438b2fbf2ed049c7def455ce9330b92a5c144c6ed753975413e14fbd6ddcf13bf3d0b708cfe79f7fed74e8b430c499597e5d12e25acf8844759142f745a4d555f6c7ee2e44d14a268b2b33c5f8431b7f97a3f87fbf1f622005f812d7fa771a9a68dd5ddfe2cff4c73eb9956c37c5323c2eef63eddaa72e87b555ef614d1597aa6b7cf0c4ed1fb1c57ae6206e8c4310a838817ab9f4fe4c5a6f667327d320616f502fb827975f367a167c658416f183c6b57fe30af08d36bbaa84d0d7d27743e28193d21dfe358bef8ef253ce3d3630b4ecad3ec8716b399d5f56af96c3c84ff8f373237c3e0a64a2fb7653fb9ee9c029cd43d4f13b194a57b6e920e7c12e1a1898f6283aff66e8c651c9a0e0cad272acfb1a08bb5cdc6f51ead8b0aa40f26fa0f834791a5d5ca86bab1332f1f0cf2e38a4961f5cdda28943b330db1524cae52055ad62866a5c240be1fd2341a769af6b2d46a25336d3de7501e990a7f7fc014f9dabccd8015eeac2a4c0490e6d6fe76fdb43dd97bc684b03bc67ea88402fbadda03802aaf7acd5c423fe97348eb153742f9f08e5272eae81ecccfb83616674b182bd132f62f76cdba6a45f53aab49b89e0229eb56df7ae17829e378fa37c9a23331359b55b1283d300bea102e642118b28457b30997d8b78389e3fd4f6590d75cf62e6557be1ec78f925ff269742d9ac343f169413b8bd7ad3ca74b556b8bfd6711d7f55fcdddebc866dbe061117943b7517415c901646198ed8111d8ba8c307d6b0a908b366a9d8b79f147c9ac044df5195a798304524cfbfdd1e651ad13f36b5c89167985a51dc579d41814fa7a978300514d8a5297601538cd140c5634092c922de6d4057a574f051fd88c7c7128bbdd923ea2ec50c1da41d37627f0f14209c62009fb389c327cf7f05e582dd11b678dd12a40179265339e9219d02222111e2876e2934c491391cd42ec84d39872ebf7add12e58a5ade7b504ca1006972606d1f130832c68fad2927f7b89fe290730ef80a7509e2baf8256f5c4a85e1ed84b8ccbaecf392de72fa6d3419ea2c30831848648c162774e1b16c53ce93e76d6d5f57061c9e616eac6433a3eee992c14417274ba31b2daa91387ab62e1529dc069edc3f2a9c1b5d6f23ab03eccc0d28541788c60f78635e77d77a6310cf66c47776cc5dae76e6678f36440bf80bab950bba6626ecb2b42a28485dac437806dd535111e9a022bc65108fafde71b79e33b59209c2269703ff7142bee9e67c8b26f37a4f34c2e9afb9aff4289ea7eba76ddc32de54ab4ff915559aa0ad72edf1554f6ada0c7793038f29326eb46d751bc4a90ca830ed6fa3316ca15f084bd241fec70379a22a41094cea26a8635715b0814335c73db340215d4c00ab07032c883d8002cdb212a89f3e7c2c99a834f8417b8a6092f8a11491cdb7202df946a65fed1a90ea90e52c93f5bb6e157975bd88433768756658f645ee6959e059953ef4760ced77997f80239e93786895e0f7530161fb4ced1ad91b760e5a290574d3f5b9885098df6806d3d2f6b5f63afe8e60aa06d6fc10d70c8d1d311a4fc75aa6cf53b9dc51a3c7951560bf65333f9ee5b313b9743f9b84206696f5aec9d3df70cc830a6072c858e2419fa2e01975764de15dbdb0dab10787770acc420a990bb4c4865686892483687c25042d06a2ba8ab7600dff29048a35c1e15c1633894f3a55c87ab3bd1b7a591fbf36b2814b3b5b1f248e29de147ef70e7310bbf0d5409573158b97724ed439aaa744ac5bc8139d74211556a6604e55c256a93faec8ef049ab40407580004ceb65a71ad206701577e09536ccff01fd76cd896c6bffc5cd16c1cbbc8149aeaad497877ecd7454c7bf8d98d1a3923a449c9513ef5003a5aae95542fcea5bbdeaba4d9facbdc8007377ff0c52f5473546374a2bed6eb42b66f24921e5de75c9a33082a2205c5b1504ec1bf52c2ad8972eb9446792e9ee21443a2ae8ba897720991b60c6133decbbb1d471c3e47c5025ab224ce4186bace4fddd2005e03f2826b276946fe3f54a5cb38abec78022305034d530227d9c0df35a88208bab267e18120ece9affd5073bcae282f29231830111131866768b9195a1a8bac1e8f62025486266788a959fb3dfe8f1fe091e20292a485a5d5e7879878a9394afc2dbde1c313d6388959ba4b5d9e3e5f4000000000000000000000000000000000000000f1d303d";
const PK2_HEX = "c95b0e20064e7dae9788b62cfd14619bdad987a08046bab6d4c83739965cf53b07cecd649ea956e0f0e1d9e852fb7e0e48d1ad9559c1488d2d2c3b67de7ab538691924a937b884705453be44ed226c45daf4e1d891a287fdcc4aa4ddb9282d1511b427df152ce8b42bc4dcbaa253f5c1513602214ce6ada7135cd6f8de022bc116c2a15e4437717fa7bc84cd529e799099a415ce88594b12e525086bcb4c26f601dee879cb22a9bbb8029b837d81d8cd3da5a39ccddafdc123970d539ac47263256c81deb23b3056b4d936c753be46b83773352bfe4c6e8a61ac993c57023905ae8ecff1433e5baf9261aaf3578b1c96c61808d4ef6334615b01176db8f4a61230b93d393c46fe34252714fe02b352e34584cfeb2b18ee5cc08c105c1ccde279dda3585609285e6cb6e5f110438a5cc8a9c4787bb75ed242f42269168cf37f9e40ac24269cd502547a748bea2e99bfc9cccc4d4c6b4c90348f6fc1029b7d3289ff389846df3540664e1981d3df93716c1467c062b30a4bf36893678277b72de0067d156d269332e7bce9c38fdb0987daaf855123972dcb4e046de213455a7f7429c8dad19914e8140772e1c2d4fc620e147cc073bbf130a34a6076ae15bac6ce3503ea46c38515cf08c53a1b5ebbd16861de10eb58438a0bf123b592764c08a215b52d67361f83dac58fb1ccc40c26af90abf2345b7e56b1f603909757a7a9f0dbce9a8c4e3caa525296e55870065f73e42090f8389013f4c169912314f9566fc06d7a5e4cbbcaedeaadff3b8c661f4c07c955914f6392d97e751a8136ae856ac7a910648acaa119d6f72c8d3c5f36a10315e18c9c052ff5a40cff9fe37e320382ff4a6f818efaeddeb3a9199bb70a01734c9ae2e5ba9c85a7698597510e3c17cda65667637989ada2ee7b192607d3c0a659cde38206f1bdd88d1ee3207e127fd2a3fe7ce8a58600fccf299c91fa1f2fa878305c3fb885a532c80c7d8b0f2aa9c3844196494ee25cda84e5d282caea69088175d99636250a9438bf161da6a3409ec0a1f79caa8dae33c49f42baaaaeab684b8e66bb6de42e288110ab39c702b1b2c87285350f07b4fd1b661ee87556f0761387c2e6ce769cab77bae2382712344bf78dfe17626ed1eb332a600368326ceb480f1cfa83a128c519b7edb3feb5ea500033913f958dec85560c626030c45486713922391e0b6cce852ae4ee2e78db1104698d9b227a7a400d7108e84b974e6bf1665a4d245bbc9188ad73057a2aff702aac7597e4db89acd8bb374154b218bcf253bf9a2f630fcd679bed56aadabbc8ba22eb56e626c91983e3a9521ca39103b4b212e9878c0846540be468a083831ce48c8ee022d2ea9f1c5a9793809603d1007fda4e7c3f171ec96c5bf0d26a6c736b7444a9650cbcc0d4ead0b3310ceffbf4fd7e925951a416835afdfd00d6b1404d22f3ff9a3e144d1431bcaa8e9907848401df9e74e16c59ce3fea2bc86d4215f3b4d81558cd710d4c0d68cd2f960c61e37fdf13e391ad360fe49dc0b440f1546a17c27f1d4461ca3b5cd8fff25b816cdc7b00ea1edb178bc4013f345e6ad1aab3e9057c447311578939bd8f7ee0de325263b1e857ecebe08e94b0e7569dd920dd11a4c0217abd49ff1e03aeeccb5ce85c5d942fc236e5cc1a91800704fc0161568c998fe93fa317fa03e665541414e761bdf889a3625446aabb3f1520230b23b3cbce1c62e9517dcd7a7d2d8b9a81b6753012855cefe7b25e14c56faaf9499507898245a24cc37e4cbe485b6451854af8e52fda002254ad67b59c2ed09547ec8dfa6899288fa7797e9ed4fb8fa68ee2010797e8bbb238f853e79b11974985";
const AUTHSIG_HEX = "afee7e19cf6f282358616090793637f84851ad028c2b11d55d9adad9fac4a06d8a14c22b0f55f8bf8bb4e5f5754df2aaa4d2f5bedc239694b752285fa404a192f99660d235269e76a96e2bb7cff49d23fc14a7f7537b056b061b65d0dc50becb036d0086fb50a1cf9cf512fb180f573ff1f3e82e599d82ae598fdc07ec16e6efc49687bebcb028b8f06621f0177bfc67e3b814368f3a57dd2c1d2e19c6df6f0c1d5f0ee2b91b47ac419ae8df19f126269a3f47290b0115f03cdad8f9cf1bbfb45c99c891cb7e78cd725310322ea81a02ee9843729bb81c1f7c087ab180e7d2371c2ddd6a7b8a20171859c0f4e35c1e13afac5adb674fc5aafcffde45271e293a5b2cfae1f51f6d6d95033b4147a79fe5dc343e6384afa65c1d6d8bc62983288a08f9c43819d97cdf476afbdcf0521f0babf033c7b555543f3e7052b58e5f2ad7611ebd1eed9230bceecdd04cd90877e9cf4de7bb92e53f82beec5176ba73cc3d6a46cf7d6f5e37edc14ae10dd57c9d913c1eefa5a2eaeb781b9286b6624e2f5e34f9bc86c970dd6c266a4c5c7ed967b3ba79d7ebbdf4408b07989412740f68e72419a84295f44bfb06dca90395c48d223f0ff90ba65b6417a80c8dfa6f2dcab04ac1fd09feb63143dd2d0bae634ad4667b471c56b852373911fd4cee354bc029558203192286112ad53ddf04b63df3f238698f595b81b108ea6e112c649b9c7fbca2904a592ab5e1e5db373d9db6dc741037df167468c87535ef83c8d044241b19388aecd9f9446c75a5680e5e8f4742de0984f04bf91683f2ddc1df67b864281a0238f02d013334ec7eeeee7a1c25ebcd473c1e1ee3ef8dd4362ead03c1e35e533094575340d28e74d4c593efb7b69aa50283f00062db1ca41a33393fc10406e018a18b307a579f53402ea38a2984ad89f41b839c265395ab48b42ad78a4f0414d6020042a8c62f9e38363771ac536127085cf3391d318db213e77535d23eb5262bab4dc02878e375beea70feac168952b671e5628c75e97a14dba80f50327b3711c8fa645dd6740d763715f4c4dfc72701cb1b9413d3e6e2c5dd28871d235eb5ad162fde6e79b629673b6f8d388701ff3c86e8e8bba91039d3f3b35f770f506b353d84e946a0659aee58d6f52c0efa45db6283d7a3be9c5ec7ca18b7d6d38a05d4aa5bbe974724617b4f7fceb89eecc2f5e707d9c0e5b6dd6fd3d5f9d4ae41059f1f37fe3ca25036108461131136270893e6b575d10afd976a083ce339f4b07f8d626e40f4c6827a4372796d407b43a46d41694a908ee95a855d8ca9086712beb1f2e208d540c7c6945523ddae691475451e7e248a5c3cbe209d885bd3a23a77c9f5387d53ac3497653ca8e6dda86b1b5f3feac5bed94c53faa73da8bf8d223143cffd3aa7712a27b2f98f7fc4515163aae17b4e8b8da79a8dd4c0da1a595c368a9a0064c9cbe515d988e7cc3fc8fef25162d1b6a8604461649d5c4e42fb276b077c198e33ca0b76ad2853c8fdff6d4c378c38876aa2079dd2326876101f08e482f13f6d30b8c7faef0556d0419d738ae579fdb6ba1c39bf4c4ca6e8d5cccc676ee40dc74432e85ae3c5eb917d361496ec5896431e390c47b36d6ba26c999e77f6db73183bef83ea2db267c6b64154191c4267571768011eb043a6ed75973c3a531129a098ef8936d6e415870f29832781b1979f274339762ad24a2fb91a715dab42826cab88b701c437cecc565c457bb0bee40c1249b5d52561b9c5f64d1a6a10c351a6efe0e18a07cc11f276fc1b81590a826e597036d98d467be0964a424c48460df34425e63fc52fc27feb24fa0960fb36724931fc37a0081223f5eb71c5d91b9388246e2c6c4e80cea38a3cfbf2e851941885bb32e3d086faf42fe53be19c1765551088c3ece2f1ce5d752f9173324b9fd1a630304e421de8781087b518bc3e26639017168a3b0b498656ac02d71b98e8faa297cad3ef33d4c6ad2674f602bb121f645b65fdb4ca0de6433e9722f912ffad682a4eb3f2340a506baab8c2763eba8da9e2ba298ca438424398300582c97cc5fc0d2585f6c8c9736090734844d2781046158bfb3557469b6683e8317f614ca4c5d08df14bac41e72efbaeea18fb012d563db7f8fde444998908deeacb905889e073a2cef13abd41f536524914e8e27f688351c312aa9ed22fec30f15e0a491147241e85050ea7a164c10eb92f8001540e1a6aecd76ddc51c03f42aac718a0d6c2419dd57dee40ba766a5a33b91e972a3b80dd20b9e1847ba70b2f0bfd2f7b273a55a1d699f8e2c195ae676f8a30bbd3f10b7b3ae47d488f2bce99ad20f0f7445d60d088bf8b1729a571fe62abba48d41fa90f89d64e843306143b1b0d701adcbbd92e684555f78d37a18c7abfa3d7a69e02de6f8be76029142a04dcc465e6130ab6597360cd341a695b03e3db6addf93af6dd8862f70216f0e392fb73a926267651cafa23d7523ff81a2c0f1935d30cd77aea0b75a0fc989604ca79d2aa10fd9936015893c93d97f67096413e7eca99288b3343cd3515ef5b345160a39964fe69e910cec7cd0850ea08c1554687cccc5a5467891fda5bb6bdf6f1489d72af11ea383b3701a24d3a207ec445b5a2986a117223e04c917acc57bff2eb8ad721a96bb5d5e85f7a18f7975faaa146c55ddef3f6a631c1473f97081b327b8dafe3562067bcd4792f834739b700a1cb052dd000edc5450a78f9d91600d8c58b1fa82889bb9be31ea617cf1e9410f8ad733f8bf5537b281c7a2c599f2cad07969f9a86acfe96c1e1f89b9c3ab108fa5004dd3875c6ee7146dd8b405e11dff1ecd3c04481e205caa0e43ac48fa3f4bf0cbe3f74b240ffd85048f9edaabfed88ad03a9b83f76cdc228638118e32af03358cf7019cff35f6f07621ca148570ff3233b15dadeabc177450c03a427a22cc7a03495113c4aea0d20d1963bc056e68706410c4ee6181c109c6bb4bd2764715feb0885fe76bf7e4cb66a825e45cfea8e46d1998713f8f93e27083b48494f23ba9d016061be1f3b560ddf46088058f369b9fa40b688d363f373ed667cd2ce8027d1912c3ce20d67c3393399f2fac9663493fc94fd2956a1ad6c8fdf06ae60b5318c6f4d0b05f879f1e1d478dd26a2b8b0298c429d23cbff0e24ca6dbde65a6ac02a664f3f3b47fefa01f4adc1b2be518fed0e2cb75cbff299d905a9e3f2b587c6226a508d080fca3ea9bde23e1e3e19614d6c98b3609fb93d7bdeaf7df604129e9aa28f92ad5cb9d79f7c0e8d04f540d3ef417e12f6f2e3aadb9c9da158f5d515213650555a8a97a7a9bbcfd7f9141536375152555a5d5f6c6e7eacbcdddff70b223a495155667c8d99aeb1b9daf5ff080b2d3141474b61636f7175787f88acb1b8bbc0c5d4d9ebfb000000000000000e203049";
// TAMPERED_HEX = SIG1_HEX with byte 100 (0x5d → 0x5c, bit 0 flipped)
const TAMPERED_HEX = "a9173657dceed160b645ffb310611c97be26defa3a12c4a84aa2a59798d7619b5dfc2e69cf27427b3f6292fa558d34161577f167a8f3d4bed7ab7e21abe8d5aaff8bc941ca3da2b2565daf0e59e1b8384a432cf68d78603b6826d94d6f6949e896c482565c27f6ee139c89fe1f71addefdbe40adadc3eaeb6f7803ed441243152ec1e05f32bf0b7b5b4b87b6f94439d42627162f8e5e712d9400817d07b83f40510b80ca04f28f85f75befd7c74c1451c4d6c38256e5d5ca53a79bec8eebd8ca8f73bd3701cff70fb35bf109a0412a7d065568386c1ed25b8ffc4237a77d1210864040f2fe8910051f4a30e96eec23463313fb5894735fad42b5ce3173b6a6c3e28790429ef7642b439151b3fc96adb3681511cd76839b40fec0c226b8d1d45c402980a20201dbd1dd1573be58e9575f4708e4bba4633a296bfa0826774bf30b397c55f3a2bef5ede66d585de14763773bbe1ad3d2e988a9e94e467191888d784a2092cc5aa172d17a07a07076c40896ed947fd9514fafb2f125aecf174e31ede1d77112e978449ef58bb54bb48678eca38323356f40b6c9fdfb1f14faaffc7f3c86f201162c2527cb705f8759d48b3301f8206a1a71a683cbe4d70b8858c7a6466eade39c3fd1c6256d75a1569ca7642f884750e3d080139fd71f4ed5a0ac2b92bb6a68128207bf1cf5eb3297fa0b2c63115c49619aa2355279202d0785485318d6bf239b6968fb289b6ffdc18f035d08a0f49d9d1322b82a7b8f30ad8c391af34c4f0e3eeb5f182f0b91dcc9571f7198f5f31342469158bff3ad1b77ae057a9e570a2f408393d05fd28ce6fb265e439ed2fc35eaecb6351aecdec57b1842d010f64a6bf4cc826609f433a40a02d311fe37572c2ec13f865a1119d607564139c8294fb450dd235df70ca052c09bfea8e600cc4ea07048677a3eb78b2ca9f1c256fbdd73d18718a273fae598314c1ea3ae3933d5ef43efd52e0919497c5a1ef8089f610dedd2d5910c5c1127ea6fbf827fb151ad666006a8161399e78fbccada995823988ff334d92406b9140ca857f64230eb5221243eac31ddce1a6cfc393bcf51e299287610eb303f6833caeedd4c29a7d15e9d434c2a23e31f85c129010df0822ebf6523ae368d8c46894f1a14dedb75ec664733b057c06f0833c11a05d07f54be77f0b9af867435f102e1b438b2fbf2ed049c7def455ce9330b92a5c144c6ed753975413e14fbd6ddcf13bf3d0b708cfe79f7fed74e8b430c499597e5d12e25acf8844759142f745a4d555f6c7ee2e44d14a268b2b33c5f8431b7f97a3f87fbf1f622005f812d7fa771a9a68dd5ddfe2cff4c73eb9956c37c5323c2eef63eddaa72e87b555ef614d1597aa6b7cf0c4ed1fb1c57ae6206e8c4310a838817ab9f4fe4c5a6f667327d320616f502fb827975f367a167c658416f183c6b57fe30af08d36bbaa84d0d7d27743e28193d21dfe358bef8ef253ce3d3630b4ecad3ec8716b399d5f56af96c3c84ff8f373237c3e0a64a2fb7653fb9ee9c029cd43d4f13b194a57b6e920e7c12e1a1898f6283aff66e8c651c9a0e0cad272acfb1a08bb5cdc6f51ead8b0aa40f26fa0f834791a5d5ca86bab1332f1f0cf2e38a4961f5cdda28943b330db1524cae52055ad62866a5c240be1fd2341a769af6b2d46a25336d3de7501e990a7f7fc014f9dabccd8015eeac2a4c0490e6d6fe76fdb43dd97bc684b03bc67ea88402fbadda03802aaf7acd5c423fe97348eb153742f9f08e5272eae81ecccfb83616674b182bd132f62f76cdba6a45f53aab49b89e0229eb56df7ae17829e378fa37c9a23331359b55b1283d300bea102e642118b28457b30997d8b78389e3fd4f6590d75cf62e6557be1ec78f925ff269742d9ac343f169413b8bd7ad3ca74b556b8bfd6711d7f55fcdddebc866dbe061117943b7517415c901646198ed8111d8ba8c307d6b0a908b366a9d8b79f147c9ac044df5195a798304524cfbfdd1e651ad13f36b5c89167985a51dc579d41814fa7a978300514d8a5297601538cd140c5634092c922de6d4057a574f051fd88c7c7128bbdd923ea2ec50c1da41d37627f0f14209c62009fb389c327cf7f05e582dd11b678dd12a40179265339e9219d02222111e2876e2934c491391cd42ec84d39872ebf7add12e58a5ade7b504ca1006972606d1f130832c68fad2927f7b89fe290730ef80a7509e2baf8256f5c4a85e1ed84b8ccbaecf392de72fa6d3419ea2c30831848648c162774e1b16c53ce93e76d6d5f57061c9e616eac6433a3eee992c14417274ba31b2daa91387ab62e1529dc069edc3f2a9c1b5d6f23ab03eccc0d28541788c60f78635e77d77a6310cf66c47776cc5dae76e6678f36440bf80bab950bba6626ecb2b42a28485dac437806dd535111e9a022bc65108fafde71b79e33b59209c2269703ff7142bee9e67c8b26f37a4f34c2e9afb9aff4289ea7eba76ddc32de54ab4ff915559aa0ad72edf1554f6ada0c7793038f29326eb46d751bc4a90ca830ed6fa3316ca15f084bd241fec70379a22a41094cea26a8635715b0814335c73db340215d4c00ab07032c883d8002cdb212a89f3e7c2c99a834f8417b8a6092f8a11491cdb7202df946a65fed1a90ea90e52c93f5bb6e157975bd88433768756658f645ee6959e059953ef4760ced77997f80239e93786895e0f7530161fb4ced1ad91b760e5a290574d3f5b9885098df6806d3d2f6b5f63afe8e60aa06d6fc10d70c8d1d311a4fc75aa6cf53b9dc51a3c7951560bf65333f9ee5b313b9743f9b84206696f5aec9d3df70cc830a6072c858e2419fa2e01975764de15dbdb0dab10787770acc420a990bb4c4865686892483687c25042d06a2ba8ab7600dff29048a35c1e15c1633894f3a55c87ab3bd1b7a591fbf36b2814b3b5b1f248e29de147ef70e7310bbf0d5409573158b97724ed439aaa744ac5bc8139d74211556a6604e55c256a93faec8ef049ab40407580004ceb65a71ad206701577e09536ccff01fd76cd896c6bffc5cd16c1cbbc8149aeaad497877ecd7454c7bf8d98d1a3923a449c9513ef5003a5aae95542fcea5bbdeaba4d9facbdc8007377ff0c52f5473546374a2bed6eb42b66f24921e5de75c9a33082a2205c5b1504ec1bf52c2ad8972eb9446792e9ee21443a2ae8ba897720991b60c6133decbbb1d471c3e47c5025ab224ce4186bace4fddd2005e03f2826b276946fe3f54a5cb38abec78022305034d530227d9c0df35a88208bab267e18120ece9affd5073bcae282f29231830111131866768b9195a1a8bac1e8f62025486266788a959fb3dfe8f1fe091e20292a485a5d5e7879878a9394afc2dbde1c313d6388959ba4b5d9e3e5f4000000000000000000000000000000000000000f1d303d";

function hexToBuffer(hex: string): Buffer {
  return Buffer.from(hex, "hex");
}

// Pre-instructions required for any tx that runs verify_dilithium3.
// requestHeapFrame(64KB): VerifyingKey pre-expands NTT matrix A (≈16 KB heap).
// setComputeUnitLimit(1.4M): ML-DSA-44 verify takes ~500K–1.2M CUs.
function verifyBudget() {
  return [
    ComputeBudgetProgram.requestHeapFrame({ bytes: 64 * 1024 }),
    ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
  ];
}

describe("falcon_verify — Initiative 06", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const connection = provider.connection;
  const payer = (provider.wallet as anchor.Wallet).payer;

  const auditMerkle  = anchor.workspace.AuditMerkle  as Program;
  const falconVerify = anchor.workspace.FalconVerify as Program;

  // Dedicated authority for this test suite — avoids PDA conflicts with
  // e2e_integration which uses payer.publicKey for PqBuffer/keyring seeds.
  const testAuthority = Keypair.generate();

  // ── Shared state ────────────────────────────────────────────────────────────
  const merkleTreeKp = Keypair.generate();
  let treeConfigPda: PublicKey;
  let treeConfigBump: number;
  let keyringPda: PublicKey;

  // PqBuffer PDAs — each (authority, slot) pair is a unique PDA.
  // slot 0: real Dilithium-3 pk / PK1 (1312 bytes, seed=1)
  // slot 1: real Dilithium-3 sig / SIG1 over test message (2420 bytes)
  // slot 2: new-key for rotate / PK2 (1312 bytes, seed=2)
  // slot 3: auth-sig for rotate / AUTHSIG = sk1.sign(pk2_bytes) (2420 bytes)
  // slot 4: bad sig — 100 bytes (wrong length, for test 3)
  // slot 5: bad pk  — 64 bytes  (wrong length, for test 4)
  // slot 6: Falcon-512 pk (897 bytes)
  // slot 7: Falcon-512 sig (690 bytes)
  // slot 8: tampered SIG1 (byte 100 flipped, for test 2b)
  let pkBufPda: PublicKey;
  let sigBufPda: PublicKey;
  let newKeyBufPda: PublicKey;
  let authSigBufPda: PublicKey;
  let badSigBufPda: PublicKey;
  let badPkBufPda: PublicKey;
  let falconPkBufPda: PublicKey;
  let falconSigBufPda: PublicKey;
  let tamperedSigBufPda: PublicKey;

  // ── Helpers ─────────────────────────────────────────────────────────────────

  function auditAccounts() {
    return {
      auditTreeConfig:    treeConfigPda,
      auditMerkleTree:    merkleTreeKp.publicKey,
      auditMerkleProgram: AUDIT_MERKLE_ID,
      compressionProgram: SPL_COMPRESSION,
      noopProgram:        SPL_NOOP,
    };
  }

  async function getTreeConfig() {
    return auditMerkle.account.treeConfig.fetch(treeConfigPda);
  }

  async function getLeafCount(): Promise<number> {
    const cfg = await getTreeConfig();
    return (cfg.leafCount as BN).toNumber();
  }

  function pqBufPda(slot: number): PublicKey {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from("pq-buf"), testAuthority.publicKey.toBuffer(), Buffer.from([slot])],
      FALCON_VERIFY_ID,
    );
    return pda;
  }

  async function initBuffer(slot: number): Promise<PublicKey> {
    const pda = pqBufPda(slot);
    await falconVerify.methods
      .initPqBuffer(slot)
      .accounts({ buffer: pda, authority: testAuthority.publicKey, systemProgram: SystemProgram.programId })
      .signers([testAuthority])
      .rpc();
    return pda;
  }

  async function writeBuffer(bufPda: PublicKey, data: Buffer): Promise<void> {
    for (let off = 0; off < data.length; off += CHUNK) {
      const chunk = data.slice(off, Math.min(off + CHUNK, data.length));
      await falconVerify.methods
        .writePqBuffer(chunk, off)
        .accounts({ buffer: bufPda, authority: testAuthority.publicKey })
        .signers([testAuthority])
        .rpc();
    }
  }

  // ── 0. Initialize audit merkle tree + all PqBuffers ──────────────────────────

  before("initializes the audit merkle tree and PqBuffer PDAs", async () => {
    // Fund the dedicated test authority
    const airdropSig = await connection.requestAirdrop(testAuthority.publicKey, 10_000_000_000);
    await connection.confirmTransaction(airdropSig, "confirmed");

    [treeConfigPda, treeConfigBump] = PublicKey.findProgramAddressSync(
      [Buffer.from("tree-config"), merkleTreeKp.publicKey.toBuffer()],
      AUDIT_MERKLE_ID,
    );

    // Tx 1: allocate the ConcurrentMerkleTree account (Agave 4.0 requires separate tx)
    const treeSize = getConcurrentMerkleTreeAccountSize(MAX_DEPTH, MAX_BUFFER_SIZE);
    const lamports = await connection.getMinimumBalanceForRentExemption(treeSize);
    const allocTx = new Transaction().add(SystemProgram.createAccount({
      fromPubkey:       payer.publicKey,
      newAccountPubkey: merkleTreeKp.publicKey,
      lamports,
      space:            treeSize,
      programId:        SPL_COMPRESSION,
    }));
    await provider.sendAndConfirm(allocTx, [payer, merkleTreeKp]);

    // Tx 2: initialize via audit_merkle CPI → SPL Compression.
    // Build instruction manually to guarantee isWritable=true on merkle_tree,
    // bypassing Anchor preflight which may see the account as non-existent.
    const initIx = await auditMerkle.methods
      .initializeMerkleTree(MAX_DEPTH, MAX_BUFFER_SIZE)
      .accounts({
        merkleTree:         merkleTreeKp.publicKey,
        treeConfig:         treeConfigPda,
        payer:              payer.publicKey,
        compressionProgram: SPL_COMPRESSION,
        noopProgram:        SPL_NOOP,
        systemProgram:      SystemProgram.programId,
      })
      .instruction();
    const mtIdx = initIx.keys.findIndex(k => k.pubkey.equals(merkleTreeKp.publicKey));
    if (mtIdx >= 0) initIx.keys[mtIdx].isWritable = true;
    await provider.sendAndConfirm(new Transaction().add(initIx), [payer]);

    const cfg = await getTreeConfig();
    assert.ok(cfg.merkleTree.equals(merkleTreeKp.publicKey));
    assert.equal((cfg.leafCount as BN).toNumber(), 0);

    // Create and fill all PqBuffer PDAs used across the tests.
    pkBufPda          = await initBuffer(0);
    sigBufPda         = await initBuffer(1);
    newKeyBufPda      = await initBuffer(2);
    authSigBufPda     = await initBuffer(3);
    badSigBufPda      = await initBuffer(4);
    badPkBufPda       = await initBuffer(5);
    falconPkBufPda    = await initBuffer(6);
    falconSigBufPda   = await initBuffer(7);
    tamperedSigBufPda = await initBuffer(8);

    await writeBuffer(pkBufPda,          hexToBuffer(PK1_HEX));
    await writeBuffer(sigBufPda,         hexToBuffer(SIG1_HEX));
    await writeBuffer(newKeyBufPda,      hexToBuffer(PK2_HEX));
    await writeBuffer(authSigBufPda,     hexToBuffer(AUTHSIG_HEX));
    await writeBuffer(badSigBufPda,      Buffer.alloc(100, 0xff)); // wrong length
    await writeBuffer(badPkBufPda,       Buffer.alloc(64,  0xff)); // wrong length
    await writeBuffer(falconPkBufPda,    Buffer.alloc(FALCON512_PK_LEN,  0xef));
    await writeBuffer(falconSigBufPda,   Buffer.alloc(FALCON512_SIG_LEN, 0x12));
    await writeBuffer(tamperedSigBufPda, hexToBuffer(TAMPERED_HEX));
  });

  // ── 1. initialize_keyring ────────────────────────────────────────────────────

  it("1. initialize_keyring creates SigningKeyring PDA and appends audit leaf", async () => {
    [keyringPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("keyring"), testAuthority.publicKey.toBuffer()],
      FALCON_VERIFY_ID,
    );

    const leafCountBefore = await getLeafCount();

    await falconVerify.methods
      .initializeKeyring(SIG_TYPE_DILITHIUM3)
      .accounts({
        keyring:       keyringPda,
        authority:     testAuthority.publicKey,
        systemProgram: SystemProgram.programId,
        keyBuffer:     pkBufPda,
        ...auditAccounts(),
      })
      .signers([testAuthority])
      .rpc();

    const keyring = await falconVerify.account.signingKeyring.fetch(keyringPda);
    assert.ok(keyring.authority.equals(testAuthority.publicKey), "authority mismatch");
    assert.deepEqual(keyring.keyType, SIG_TYPE_DILITHIUM3, "key_type should be Dilithium3");
    assert.equal(keyring.publicKey.length, DILITHIUM3_PK_LEN, "public_key wrong length");
    assert.equal(keyring.rotationCount, 0, "rotation_count should start at 0");

    const leafCountAfter = await getLeafCount();
    assert.equal(leafCountAfter, leafCountBefore + 1, "audit leaf not appended");
  });

  // ── 2. verify_signature — real ML-DSA-44 test vectors, correct lengths ──────
  // On-chain verify_dilithium3 is a structural stub (see BPF note at top of file).
  // Real ML-DSA-44 cryptographic rejection of tampered sigs is tested in the
  // Rust unit tests (cargo test -p falcon_verify).

  it("2. verify_signature accepts correct-length ML-DSA-44 sig/pk (on-chain stub)", async () => {
    const msg = Buffer.from("zynt-protocol-test-message");

    await falconVerify.methods
      .verifySignature(SIG_TYPE_DILITHIUM3, msg)
      .accounts({
        signer:    testAuthority.publicKey,
        sigBuffer: sigBufPda,
        pkBuffer:  pkBufPda,
      })
      .signers([testAuthority])
      .rpc();
  });

  // ── 3. verify_signature — wrong sig length → BadSignatureLength ───────────────

  it("3. verify_signature rejects Dilithium-3 sig with wrong length", async () => {
    const msg = Buffer.from("zynt-test");

    try {
      await falconVerify.methods
        .verifySignature(SIG_TYPE_DILITHIUM3, msg)
        .accounts({
          signer:    testAuthority.publicKey,
          sigBuffer: badSigBufPda, // 100 bytes — wrong length
          pkBuffer:  pkBufPda,
        })
        .signers([testAuthority])
        .rpc();
      assert.fail("Expected BadSignatureLength error");
    } catch (err: any) {
      assert.include(
        err.toString(),
        "BadSignatureLength",
        `Expected BadSignatureLength, got: ${err}`,
      );
    }
  });

  // ── 4. verify_signature — wrong pk length → BadPublicKeyLength ───────────────

  it("4. verify_signature rejects Dilithium-3 pk with wrong length", async () => {
    const msg = Buffer.from("zynt-test");

    try {
      await falconVerify.methods
        .verifySignature(SIG_TYPE_DILITHIUM3, msg)
        .accounts({
          signer:    testAuthority.publicKey,
          sigBuffer: sigBufPda,
          pkBuffer:  badPkBufPda, // 64 bytes — wrong length
        })
        .signers([testAuthority])
        .rpc();
      assert.fail("Expected BadPublicKeyLength error");
    } catch (err: any) {
      assert.include(
        err.toString(),
        "BadPublicKeyLength",
        `Expected BadPublicKeyLength, got: ${err}`,
      );
    }
  });

  // ── 5. rotate_signing_key — authorized rotation ───────────────────────────────

  it("5. rotate_signing_key updates keyring PDA and appends audit leaf", async () => {
    const leafCountBefore = await getLeafCount();

    await falconVerify.methods
      .rotateSigningKey(SIG_TYPE_DILITHIUM3)
      .accounts({
        keyring:       keyringPda,
        authority:     testAuthority.publicKey,
        newKeyBuffer:  newKeyBufPda,
        authSigBuffer: authSigBufPda,
        ...auditAccounts(),
      })
      .signers([testAuthority])
      .rpc();

    const keyring = await falconVerify.account.signingKeyring.fetch(keyringPda);
    assert.deepEqual(keyring.keyType, SIG_TYPE_DILITHIUM3, "key_type mismatch after rotation");
    assert.equal(keyring.rotationCount, 1, "rotation_count should be 1 after first rotation");
    assert.equal(keyring.publicKey.length, DILITHIUM3_PK_LEN);
    // PK2 (seed=2) starts with 0xc9 — confirms the new key was stored correctly
    assert.equal(keyring.publicKey[0], 0xc9, "new pk not stored correctly");

    const leafCountAfter = await getLeafCount();
    assert.equal(leafCountAfter, leafCountBefore + 1, "audit leaf not appended on rotation");
  });

  // ── 6. rotate_signing_key — unauthorized (wrong authority) ────────────────────

  it("6. rotate_signing_key rejects when authority does not own the keyring", async () => {
    const rogue = Keypair.generate();
    const sig = await connection.requestAirdrop(rogue.publicKey, 1_000_000_000);
    await connection.confirmTransaction(sig, "confirmed");

    try {
      // keyringPda is owned by testAuthority; authority is rogue → has_one fails
      await falconVerify.methods
        .rotateSigningKey(SIG_TYPE_DILITHIUM3)
        .accounts({
          keyring:       keyringPda,
          authority:     rogue.publicKey,
          newKeyBuffer:  newKeyBufPda,
          authSigBuffer: authSigBufPda,
          ...auditAccounts(),
        })
        .signers([rogue])
        .rpc();
      assert.fail("Expected RotationNotAuthorized error");
    } catch (err: any) {
      assert.ok(
        err.toString().includes("RotationNotAuthorized") ||
        err.toString().includes("ConstraintHasOne") ||
        err.toString().includes("ConstraintSeeds") ||
        err.toString().includes("PqBufferNotOwned") ||
        err.toString().includes("2003") ||
        err.toString().includes("2006"),
        `Expected authorization error, got: ${err}`,
      );
    }
  });

  // ── 7. Falcon-512 → FalconNotYetSupported (no simd-0416 feature) ─────────────

  it("7. verify_signature returns FalconNotYetSupported for Falcon-512 without simd-0416", async () => {
    const msg = Buffer.from("zynt-falcon-test");

    try {
      await falconVerify.methods
        .verifySignature(SIG_TYPE_FALCON512, msg)
        .accounts({
          signer:    testAuthority.publicKey,
          sigBuffer: falconSigBufPda,
          pkBuffer:  falconPkBufPda,
        })
        .signers([testAuthority])
        .rpc();
      assert.fail("Expected FalconNotYetSupported error");
    } catch (err: any) {
      assert.include(
        err.toString(),
        "FalconNotYetSupported",
        `Expected FalconNotYetSupported, got: ${err}`,
      );
    }
  });

  // ── PQ Verifier Interface (additive) ──────────────────────────────────────
  //
  // Tests for the swappable verification backend:
  //   init_pq_verifier_config / verify_pq_signature / set_mode
  //
  // These are additive — the legacy verify_signature instruction and all
  // seven tests above remain untouched.

  describe("PQ Verifier Interface (additive)", () => {
    // Two governance authorities:
    //   multisigAuth — localnet config (cluster_is_mainnet = false)
    //   mainnetAuth  — mainnet config  (cluster_is_mainnet = true)
    const multisigAuth = Keypair.generate();
    const mainnetAuth  = Keypair.generate();
    const rogueUser    = Keypair.generate();

    let configPda: PublicKey;        // localnet config PDA
    let mainnetConfigPda: PublicKey; // mainnet config PDA (for StubForbiddenOnMainnet tests)

    const PQ_SCHEME_MLDSA44 = { mlDsa44:   {} };
    const MODE_STUB          = { stub:          {} };
    const MODE_SYSCALL       = { syscall:       {} };

    before("fund authorities, init localnet and mainnet PqVerifierConfig PDAs", async () => {
      // Fund all three keypairs
      for (const kp of [multisigAuth, mainnetAuth, rogueUser]) {
        const s = await connection.requestAirdrop(kp.publicKey, 5_000_000_000);
        await connection.confirmTransaction(s, "confirmed");
      }

      [configPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("pq-verifier-config"), multisigAuth.publicKey.toBuffer()],
        FALCON_VERIFY_ID,
      );
      [mainnetConfigPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("pq-verifier-config"), mainnetAuth.publicKey.toBuffer()],
        FALCON_VERIFY_ID,
      );

      // localnet config: cluster_is_mainnet = false, scheme = MlDsa44
      await falconVerify.methods
        .initPqVerifierConfig(false, PQ_SCHEME_MLDSA44)
        .accounts({
          config:        configPda,
          authority:     multisigAuth.publicKey,
          systemProgram: SystemProgram.programId,
          ...auditAccounts(),
        })
        .signers([multisigAuth])
        .rpc();

      // mainnet config: cluster_is_mainnet = true, scheme = MlDsa44
      await falconVerify.methods
        .initPqVerifierConfig(true, PQ_SCHEME_MLDSA44)
        .accounts({
          config:        mainnetConfigPda,
          authority:     mainnetAuth.publicKey,
          systemProgram: SystemProgram.programId,
          ...auditAccounts(),
        })
        .signers([mainnetAuth])
        .rpc();
    });

    // ── 8. init_pq_verifier_config ──────────────────────────────────────────

    it("8. init_pq_verifier_config stores authority, scheme, mode=Stub, and mainnet flag", async () => {
      const config = await falconVerify.account.pqVerifierConfig.fetch(configPda);
      assert.ok(config.authority.equals(multisigAuth.publicKey), "authority mismatch");
      assert.equal(config.clusterIsMainnet, false, "clusterIsMainnet should be false");
      assert.deepEqual(config.defaultScheme, PQ_SCHEME_MLDSA44, "default scheme mismatch");
      assert.deepEqual(config.mode, MODE_STUB, "initial mode should be Stub");

      const mainnetConfig = await falconVerify.account.pqVerifierConfig.fetch(mainnetConfigPda);
      assert.equal(mainnetConfig.clusterIsMainnet, true, "mainnet config flag wrong");
    });

    // ── 9. verify_pq_signature — Stub dispatches and accepts correct lengths ──

    it("9. verify_pq_signature dispatches to Stub backend and accepts correct-length sig/pk", async () => {
      const msg = Buffer.from("zynt-protocol-test-message");
      await falconVerify.methods
        .verifyPqSignature(PQ_SCHEME_MLDSA44, msg)
        .accounts({
          config:    configPda,
          signer:    multisigAuth.publicKey,
          sigBuffer: sigBufPda,
          pkBuffer:  pkBufPda,
        })
        .signers([multisigAuth])
        .rpc();
    });

    // ── 10. StubForbiddenOnMainnet guard in verify_pq_signature ───────────────

    it("10. verify_pq_signature Stub backend rejects on mainnet config (StubForbiddenOnMainnet)", async () => {
      const msg = Buffer.from("zynt-protocol-test-message");
      try {
        await falconVerify.methods
          .verifyPqSignature(PQ_SCHEME_MLDSA44, msg)
          .accounts({
            config:    mainnetConfigPda,
            signer:    mainnetAuth.publicKey,
            sigBuffer: sigBufPda,
            pkBuffer:  pkBufPda,
          })
          .signers([mainnetAuth])
          .rpc();
        assert.fail("Expected StubForbiddenOnMainnet");
      } catch (err: any) {
        assert.include(
          err.toString(),
          "StubForbiddenOnMainnet",
          `Expected StubForbiddenOnMainnet, got: ${err}`,
        );
      }
    });

    // ── 11. set_mode — non-authority rejected ─────────────────────────────────

    it("11. set_mode rejected when caller is not the config authority", async () => {
      try {
        // rogueUser passes itself as authority; Anchor re-derives the PDA from
        // rogue's key → seed mismatch → ConstraintSeeds before has_one is checked.
        await falconVerify.methods
          .setMode(MODE_SYSCALL)
          .accounts({
            config:    configPda,
            authority: rogueUser.publicKey,
            ...auditAccounts(),
          })
          .signers([rogueUser])
          .rpc();
        assert.fail("Expected authorization error");
      } catch (err: any) {
        assert.ok(
          err.toString().includes("UnauthorizedModeChange") ||
          err.toString().includes("ConstraintHasOne") ||
          err.toString().includes("ConstraintSeeds") ||
          err.toString().includes("2003") ||
          err.toString().includes("2006"),
          `Expected authorization error, got: ${err}`,
        );
      }
    });

    // ── 12. set_mode — authorized mode change + audit leaf ────────────────────

    it("12. set_mode changes mode to Syscall and appends audit leaf", async () => {
      const leafCountBefore = await getLeafCount();

      await falconVerify.methods
        .setMode(MODE_SYSCALL)
        .accounts({
          config:    configPda,
          authority: multisigAuth.publicKey,
          ...auditAccounts(),
        })
        .signers([multisigAuth])
        .rpc();

      const config = await falconVerify.account.pqVerifierConfig.fetch(configPda);
      assert.deepEqual(config.mode, MODE_SYSCALL, "mode should now be Syscall");

      const leafCountAfter = await getLeafCount();
      assert.equal(leafCountAfter, leafCountBefore + 1, "audit leaf not appended by set_mode");
    });

    // ── 13. verify_pq_signature — Syscall mode returns SyscallUnavailable ─────

    it("13. verify_pq_signature in Syscall mode returns SyscallUnavailable", async () => {
      const msg = Buffer.from("zynt-protocol-test-message");
      try {
        await falconVerify.methods
          .verifyPqSignature(PQ_SCHEME_MLDSA44, msg)
          .accounts({
            config:    configPda,
            signer:    multisigAuth.publicKey,
            sigBuffer: sigBufPda,
            pkBuffer:  pkBufPda,
          })
          .signers([multisigAuth])
          .rpc();
        assert.fail("Expected SyscallUnavailable");
      } catch (err: any) {
        assert.include(
          err.toString(),
          "SyscallUnavailable",
          `Expected SyscallUnavailable, got: ${err}`,
        );
      }
    });

    // ── 14. set_mode rejects Stub when cluster_is_mainnet ─────────────────────

    it("14. set_mode rejects setting Stub mode when cluster_is_mainnet is true (StubForbiddenOnMainnet)", async () => {
      // mainnet config currently has mode=Stub but the guard fires in set_mode too
      try {
        await falconVerify.methods
          .setMode(MODE_STUB)
          .accounts({
            config:    mainnetConfigPda,
            authority: mainnetAuth.publicKey,
            ...auditAccounts(),
          })
          .signers([mainnetAuth])
          .rpc();
        assert.fail("Expected StubForbiddenOnMainnet");
      } catch (err: any) {
        assert.include(
          err.toString(),
          "StubForbiddenOnMainnet",
          `Expected StubForbiddenOnMainnet, got: ${err}`,
        );
      }
    });

    // ── 15. additive — existing verify_signature still works under Stub mode ───

    it("15. existing verify_signature and new verify_pq_signature both work in Stub mode (additive)", async () => {
      // Restore localnet config to Stub so this test is self-contained
      await falconVerify.methods
        .setMode(MODE_STUB)
        .accounts({
          config:    configPda,
          authority: multisigAuth.publicKey,
          ...auditAccounts(),
        })
        .signers([multisigAuth])
        .rpc();

      const msg = Buffer.from("zynt-protocol-test-message");

      // Legacy instruction (called by hybrid_vault CPI) — must be unchanged
      await falconVerify.methods
        .verifySignature(SIG_TYPE_DILITHIUM3, msg)
        .accounts({
          signer:    testAuthority.publicKey,
          sigBuffer: sigBufPda,
          pkBuffer:  pkBufPda,
        })
        .signers([testAuthority])
        .rpc();

      // New stable entry point — Stub mode, same PqBuffers
      await falconVerify.methods
        .verifyPqSignature(PQ_SCHEME_MLDSA44, msg)
        .accounts({
          config:    configPda,
          signer:    multisigAuth.publicKey,
          sigBuffer: sigBufPda,
          pkBuffer:  pkBufPda,
        })
        .signers([multisigAuth])
        .rpc();
    });
  });
});
